FROM python
WORKDIR /app
COPY ./ remove_sw
RUN pip install pandas
RUN pip install nltk
RUN python -m nltk.downloader stopwords punkt
RUN pip install --no-cache-dir nltk 
CMD python remove_sw 
